<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>syc_pm_server.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\syc-pm-server.Domain\syc-pm-server.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

</Project>
