// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using syc_pm_server.Infrastructure.Persistence;

#nullable disable

namespace syc_pm_server.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720113517_UpdateEntitiesForLoginFlow")]
    partial class UpdateEntitiesForLoginFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("syc_pm_server.Domain.Entities.PwEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PwEntries");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.PwEntryAccess", b =>
                {
                    b.Property<Guid>("PwEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedEntryKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PwEntryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PwEntryAccesses");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pbkdf2Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.PwEntryAccess", b =>
                {
                    b.HasOne("syc_pm_server.Domain.Entities.PwEntry", "PwEntry")
                        .WithMany("AuthorizedUsers")
                        .HasForeignKey("PwEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("syc_pm_server.Domain.Entities.User", "User")
                        .WithMany("PwEntryAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PwEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.PwEntry", b =>
                {
                    b.Navigation("AuthorizedUsers");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.User", b =>
                {
                    b.Navigation("PwEntryAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
