// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using syc_pm_server.Infrastructure.Persistence;

#nullable disable

namespace syc_pm_server.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617060750_AddUniqueUsernameIndex")]
    partial class AddUniqueUsernameIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("syc_pm_server.Domain.Entities.PwEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VaultId");

                    b.ToTable("PwEntries");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.VaultMember", b =>
                {
                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedVaultKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VaultId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("VaultMembers");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.PwEntry", b =>
                {
                    b.HasOne("syc_pm_server.Domain.Entities.Vault", "Vault")
                        .WithMany("PasswordEntries")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.VaultMember", b =>
                {
                    b.HasOne("syc_pm_server.Domain.Entities.User", "User")
                        .WithMany("VaultMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("syc_pm_server.Domain.Entities.Vault", "Vault")
                        .WithMany("Members")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.User", b =>
                {
                    b.Navigation("VaultMembers");
                });

            modelBuilder.Entity("syc_pm_server.Domain.Entities.Vault", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PasswordEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
